policies:
  - type: commit
    spec:
      headerLength: 89
      dco: true
      gpg: false
      imperative: true
      maximumOfOneCommit: true
      requireCommitBody: true
      conventional:
        types:
          - chore
          - docs
          - perf
          - refactor
          - style
          - test
  - type: license
    spec:
      skipPaths:
        - .git/
        - .buildkit/
      includeSuffixes:
        - .go
      excludeSuffixes:
        - .deepcopy.go
      header: |
        // This Source Code Form is subject to the terms of the Mozilla Public
        // License, v. 2.0. If a copy of the MPL was not distributed with this
        // file, You can obtain one at http://mozilla.org/MPL/2.0/.
