---
kind: pipeline
type: kubernetes
name: default

steps:
  - name: setup-ci
    image: autonomy/build-container:latest
    commands:
      - git fetch --tags
      - install-ci-key
      - setup-buildx-amd64-arm64
    environment:
      SSH_KEY:
        from_secret: ssh_key
    resources:
      requests:
        cpu: 24000
        memory: 48GiB
    volumes:
      - name: outer-docker-socket
        path: /var/outer-run
      - name: docker-socket
        path: /var/run
      - name: buildx
        path: /root/.docker/buildx
      - name: ssh
        path: /root/.ssh

  - name: build-pull-request
    image: autonomy/build-container:latest
    pull: always
    commands:
      - make
    when:
      event:
        include:
          - pull_request
    volumes:
      - name: outer-docker-socket
        path: /var/outer-run
      - name: docker-socket
        path: /var/run
      - name: buildx
        path: /root/.docker/buildx
      - name: ssh
        path: /root/.ssh

  - name: build-and-publish
    image: autonomy/build-container:latest
    pull: always
    environment:
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
    commands:
      - docker login --username "$${DOCKER_USERNAME}" --password "$${DOCKER_PASSWORD}"
      - make PUSH=true
    when:
      event:
        exclude:
          - pull_request
    volumes:
      - name: outer-docker-socket
        path: /var/outer-run
      - name: docker-socket
        path: /var/run
      - name: buildx
        path: /root/.docker/buildx
      - name: ssh
        path: /root/.ssh

  - name: build-yaml
    image: autonomy/build-container:latest
    pull: always
    commands:
      - make release
    when:
      event:
        - tag
    volumes:
      - name: outer-docker-socket
        path: /var/outer-run
      - name: docker-socket
        path: /var/run
      - name: buildx
        path: /root/.docker/buildx
      - name: ssh
        path: /root/.ssh

  - name: release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      checksum:
        - sha256
        - sha512
      draft: true
      files:
        - _out/*
    when:
      event:
        - tag

services:
  - name: docker
    image: docker:19.03-dind
    entrypoint:
      - dockerd
    commands:
      - --dns=8.8.8.8
      - --dns=8.8.4.4
      - --mtu=1500
      - --log-level=error
      - --insecure-registry=http://registry.ci.svc:5000
    privileged: true
    volumes:
      - name: outer-docker-socket
        path: /var/outer-run
      - name: docker-socket
        path: /var/run
      - name: buildx
        path: /root/.docker/buildx
      - name: ssh
        path: /root/.ssh

volumes:
  - name: outer-docker-socket
    host:
      path: /var/ci-docker
  - name: docker-socket
    temp:
      medium: memory
  - name: buildx
    temp:
      medium: memory
  - name: ssh
    temp:
      medium: memory

---
kind: pipeline
type: kubernetes
name: notify

clone:
  disable: true

steps:
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: proj-talos-maintainers
    when:
      status:
        - success
        - failure

trigger:
  status:
    - success
    - failure

depends_on:
  - default
